{{ if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: {{ include "loki.serviceAccountName" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}


{{- if .Values.rbac.pspEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
rules:
  - apiGroups:      
      - policy
    resources:      
      - podsecuritypolicies
    verbs:          
      - use
    resourceNames:  
      - {{ include "loki.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "loki.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "loki.serviceAccountName" . }}
{{- end }}


{{ if .Values.rbac.sccEnabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scc:hostmount-anyuid
  labels:
    {{- include "loki.labels" . | nindent 4 }}
rules:
- apiGroups: ['security.openshift.io']
  resources: ['securitycontextconstraints']
  verbs:     ['use']
  resourceNames:
  - hostmount-anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:loki
  labels:
    {{- include "loki.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc:hostmount-anyuid
subjects:
- kind: ServiceAccount
  name: loki
  name: {{ include "loki.serviceAccountName" . }}

{{- end }}
{{- end }}

