{{- if .Values.graphite.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "enterprise-metrics.fullname" . }}-graphite-schemas
  labels:
    app: {{ template "enterprise-metrics.name" . }}
    chart: {{ template "enterprise-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range  $storageSchemas := toStrings .Values.graphite_querier.schemasConfiguration.storageSchemas }}
  storage-schemas.conf: |
{{ $storageSchemas | indent 4}}
{{- end }}

{{- range  $storageAggregations := toStrings .Values.graphite_querier.schemasConfiguration.storageAggregations }}
  storage-aggregations.conf: |
{{ $storageAggregations | indent 4}}
{{- end }}
{{- end -}}
