{{- if not .Values.useExternalConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalConfigSecretName }}
  labels:
    app: {{ template "enterprise-metrics.name" . }}
    chart: {{ template "enterprise-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  mimir.yaml: {{ include "enterprise-metrics.calculatedConfig" . | b64enc }}
{{- end }}
