apiVersion: v2
version: 2.0.0
appVersion: v2.0.0
description: "Grafana Enterprise Metrics"
engine: gotpl
home: https://grafana.com/products/enterprise/metrics
icon: https://grafana.com/static/img/menu/metrics-enterprise.svg
kubeVersion: ^1.10.0-0
name: enterprise-metrics
dependencies:
  - name: memcached
    alias: memcached
    version: 5.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: memcached.enabled
  - name: memcached
    alias: memcached-queries
    version: 5.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-queries.enabled
  - name: memcached
    alias: memcached-metadata
    version: 5.5.2
    repository: https://charts.bitnami.com/bitnami
    condition: memcached-metadata.enabled
  - name: mimir-distributed
    alias: mimir
    version: 2.0.0
    repository: https://grafana.github.io/helm-charts
